### ISSUE TITLE
Revisión de posibles errores en el código

### ISSUE THREAD

**Issue by mfrubio** [optimizacion-2-2021-1-gh-classroom/practica-2-primera-parte-yefovar#5]

**Comment by yefovar** [comment]
Se hicieron los siguientes ajustes para optimizar y mejorar el proceso de optimizacion

- [x]  Ajustar inputs de la funcion simplex
- [x]  Mostrar solucion del problema, valor optimizado y estatus de la optimizacion
- [x]  Corregir programacion de problemas infeasibles
- [x]  Cotejar resultados contra tres paquetes de python
